# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bwcc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CMM_Parse(object):
    def setupUi(self, CMM_Parse):
        CMM_Parse.setObjectName("CMM_Parse")
        CMM_Parse.setEnabled(True)
        CMM_Parse.resize(1439, 795)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        CMM_Parse.setFont(font)
        CMM_Parse.setStyleSheet("*{\n"
"font-size:18px;\n"
"background-color:lightblue;\n"
"}QPushButton:hover{\n"
"background:transparent;\n"
"background:skyblue;\n"
"}QTextEdit{\n"
"background:white;\n"
"}")
        self.openButton = QtWidgets.QPushButton(CMM_Parse)
        self.openButton.setGeometry(QtCore.QRect(467, 15, 31, 31))
        self.openButton.setStyleSheet("QPushButton{\n"
"border-image:url(:/reses/res/open.png);\n"
"}")
        self.openButton.setText("")
        self.openButton.setObjectName("openButton")
        self.saveButton = QtWidgets.QPushButton(CMM_Parse)
        self.saveButton.setGeometry(QtCore.QRect(522, 15, 31, 31))
        self.saveButton.setStyleSheet("QPushButton{\n"
"border-image:url(:/reses/res/save.png);\n"
"}")
        self.saveButton.setText("")
        self.saveButton.setObjectName("saveButton")
        self.parseButton = QtWidgets.QPushButton(CMM_Parse)
        self.parseButton.setGeometry(QtCore.QRect(577, 15, 30, 30))
        self.parseButton.setStyleSheet("QPushButton{\n"
"border-image:url(:/reses/res/parse.png);\n"
"}")
        self.parseButton.setText("")
        self.parseButton.setObjectName("parseButton")
        self.exitButton = QtWidgets.QPushButton(CMM_Parse)
        self.exitButton.setGeometry(QtCore.QRect(688, 15, 35, 31))
        self.exitButton.setStyleSheet("QPushButton{\n"
"border-image:url(:/reses/res/exit.png);\n"
"}")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")
        self.someEdit = QtWidgets.QTextEdit(CMM_Parse)
        self.someEdit.setEnabled(True)
        self.someEdit.setGeometry(QtCore.QRect(15, 60, 851, 451))
        self.someEdit.setObjectName("someEdit")
        self.treeEdit = QtWidgets.QTextEdit(CMM_Parse)
        self.treeEdit.setEnabled(True)
        self.treeEdit.setGeometry(QtCore.QRect(876, 60, 551, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeEdit.sizePolicy().hasHeightForWidth())
        self.treeEdit.setSizePolicy(sizePolicy)
        self.treeEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.treeEdit.setObjectName("treeEdit")
        self.resultEdit = QtWidgets.QTextEdit(CMM_Parse)
        self.resultEdit.setEnabled(True)
        self.resultEdit.setGeometry(QtCore.QRect(15, 521, 851, 259))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultEdit.sizePolicy().hasHeightForWidth())
        self.resultEdit.setSizePolicy(sizePolicy)
        self.resultEdit.setObjectName("resultEdit")
        self.runButton = QtWidgets.QPushButton(CMM_Parse)
        self.runButton.setGeometry(QtCore.QRect(635, 15, 31, 31))
        self.runButton.setStyleSheet("QPushButton{\n"
"border-image:url(:/reses/res/start.png);\n"
"}")
        self.runButton.setText("")
        self.runButton.setObjectName("runButton")
        self.pushButton = QtWidgets.QPushButton(CMM_Parse)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(876, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(CMM_Parse)
        self.openButton.clicked.connect(CMM_Parse.openButtonClicked)
        self.saveButton.clicked.connect(CMM_Parse.saveButtonClicked)
        self.parseButton.clicked.connect(CMM_Parse.parseButtonClicked)
        self.exitButton.clicked.connect(CMM_Parse.exitClicked)
        self.runButton.clicked.connect(CMM_Parse.runClicked)
        self.pushButton.clicked.connect(CMM_Parse.treeButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(CMM_Parse)

    def retranslateUi(self, CMM_Parse):
        _translate = QtCore.QCoreApplication.translate
        CMM_Parse.setWindowTitle(_translate("CMM_Parse", "Dialog"))
        self.pushButton.setText(_translate("CMM_Parse", "语 法 树"))
import pics_rc
